export const mockHelpers = [
    {
        id: 1,
        name: "Priya Sharma",
        age: 28,
        avatar: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?w=200",
        rating: 4.8,
        reviewCount: 127,
        hourlyRate: 250,
        categories: ["Event Support", "Elder Care", "Home Functions"],
        bio: "Experienced in elderly care and event management. Verified and trusted by 100+ families.",
        verified: true,
        location: "Mumbai, Maharashtra",
        responseTime: "10 mins",
        completedJobs: 134,
        availability: ["Monday", "Wednesday", "Friday", "Saturday"],
        skills: ["Patient care", "Event coordination", "Cooking"],
    },
    {
        id: 2,
        name: "Rahul Mehta",
        age: 32,
        avatar: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?w=200",
        rating: 4.9,
        reviewCount: 203,
        hourlyRate: 300,
        categories: ["Errands", "Shopping", "Delivery"],
        bio: "Quick and reliable helper for all your errand needs. Own vehicle available.",
        verified: true,
        location: "Delhi NCR",
        responseTime: "5 mins",
        completedJobs: 245,
        availability: ["Monday", "Tuesday", "Thursday", "Friday", "Sunday"],
        skills: ["Driving", "Shopping assistance", "Quick delivery"],
    },
    {
        id: 3,
        name: "Anjali Desai",
        age: 25,
        avatar: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?w=200",
        rating: 4.7,
        reviewCount: 89,
        hourlyRate: 200,
        categories: ["Companionship", "Reading Support", "Elder Care"],
        bio: "Warm and caring companion for elderly. Fluent in Hindi, English, and Gujarati.",
        verified: true,
        location: "Ahmedabad, Gujarat",
        responseTime: "15 mins",
        completedJobs: 92,
        availability: [
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Saturday",
            "Sunday",
        ],
        skills: ["Reading", "Conversation", "Basic medical assistance"],
    },
    {
        id: 4,
        name: "Vikram Singh",
        age: 35,
        avatar: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?w=200",
        rating: 4.6,
        reviewCount: 156,
        hourlyRate: 350,
        categories: ["Event Support", "Security", "Crowd Management"],
        bio: "Former security professional. Perfect for large events and gatherings.",
        verified: true,
        location: "Bangalore, Karnataka",
        responseTime: "8 mins",
        completedJobs: 178,
        availability: ["Friday", "Saturday", "Sunday"],
        skills: ["Security", "Crowd control", "Emergency response"],
    },
    {
        id: 5,
        name: "Meera Iyer",
        age: 30,
        avatar: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?w=200",
        rating: 4.9,
        reviewCount: 178,
        hourlyRate: 280,
        categories: ["Home Functions", "Cooking", "Event Support"],
        bio: "Traditional cook specializing in South Indian cuisine. Perfect for home functions.",
        verified: true,
        location: "Chennai, Tamil Nadu",
        responseTime: "12 mins",
        completedJobs: 189,
        availability: ["Monday", "Wednesday", "Friday", "Saturday", "Sunday"],
        skills: ["Traditional cooking", "Menu planning", "Event catering"],
    },
    {
        id: 6,
        name: "Amit Patel",
        age: 27,
        avatar: "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?w=200",
        rating: 4.5,
        reviewCount: 67,
        hourlyRate: 220,
        categories: ["Errands", "Pet Care", "Shopping"],
        bio: "Animal lover and reliable helper. Can help with pet sitting and daily errands.",
        verified: true,
        location: "Pune, Maharashtra",
        responseTime: "20 mins",
        completedJobs: 71,
        availability: ["Monday", "Tuesday", "Wednesday", "Thursday"],
        skills: ["Pet care", "Shopping", "Basic grooming"],
    },
];

export const mockBookings = [
    {
        id: 1,
        helperId: 1,
        helperName: "Priya Sharma",
        helperAvatar:
            "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?w=200",
        category: "Elder Care",
        date: "2026-02-15",
        timeSlot: "10:00 AM - 2:00 PM",
        hours: 4,
        rate: 250,
        total: 1000,
        status: "upcoming",
        location: "Green Park, Delhi",
        description:
            "Need assistance for elderly parent - companionship and basic care",
    },
    {
        id: 2,
        helperId: 2,
        helperName: "Rahul Mehta",
        helperAvatar:
            "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?w=200",
        category: "Errands",
        date: "2026-02-13",
        timeSlot: "3:00 PM - 5:00 PM",
        hours: 2,
        rate: 300,
        total: 600,
        status: "completed",
        location: "Sector 18, Noida",
        description: "Grocery shopping and pharmacy pickup",
        rating: 5,
        review: "Very prompt and reliable!",
    },
    {
        id: 3,
        helperId: 5,
        helperName: "Meera Iyer",
        helperAvatar:
            "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?w=200",
        category: "Home Functions",
        date: "2026-02-18",
        timeSlot: "4:00 PM - 9:00 PM",
        hours: 5,
        rate: 280,
        total: 1400,
        status: "pending",
        location: "Indiranagar, Bangalore",
        description: "Traditional dinner preparation for family gathering",
    },
];

export const mockCategories = [
    {
        id: 1,
        name: "Elder Care",
        icon: "👴",
        description: "Companionship and assistance for elderly",
        helperCount: 45,
    },
    {
        id: 2,
        name: "Event Support",
        icon: "🎉",
        description: "Help with events and gatherings",
        helperCount: 78,
    },
    {
        id: 3,
        name: "Home Functions",
        icon: "🏠",
        description: "Assistance with home-based events",
        helperCount: 62,
    },
    {
        id: 4,
        name: "Errands",
        icon: "🛒",
        description: "Shopping, delivery, and daily tasks",
        helperCount: 91,
    },
    {
        id: 5,
        name: "Companionship",
        icon: "💬",
        description: "Social support and conversation",
        helperCount: 34,
    },
    {
        id: 6,
        name: "Pet Care",
        icon: "🐕",
        description: "Pet sitting and walking",
        helperCount: 28,
    },
];

export const mockChats = [
    {
        id: 1,
        helperId: 1,
        helperName: "Priya Sharma",
        helperAvatar:
            "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?w=200",
        lastMessage: "I'll be there at 10 AM sharp!",
        timestamp: "2026-02-12T09:30:00",
        unread: 2,
        messages: [
            {
                id: 1,
                senderId: "customer",
                text: "Hi, I need someone for elder care on Feb 15th",
                timestamp: "2026-02-12T08:00:00",
            },
            {
                id: 2,
                senderId: 1,
                text: "Hello! I'd be happy to help. What time would you need me?",
                timestamp: "2026-02-12T08:15:00",
            },
            {
                id: 3,
                senderId: "customer",
                text: "10 AM to 2 PM would be perfect",
                timestamp: "2026-02-12T08:20:00",
            },
            {
                id: 4,
                senderId: 1,
                text: "I'll be there at 10 AM sharp!",
                timestamp: "2026-02-12T09:30:00",
            },
        ],
    },
    {
        id: 2,
        helperId: 2,
        helperName: "Rahul Mehta",
        helperAvatar:
            "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?w=200",
        lastMessage: "Thank you for the great review!",
        timestamp: "2026-02-13T17:30:00",
        unread: 0,
        messages: [
            {
                id: 1,
                senderId: "customer",
                text: "Can you help with grocery shopping today?",
                timestamp: "2026-02-13T14:00:00",
            },
            {
                id: 2,
                senderId: 2,
                text: "Yes, I'm available from 3 PM",
                timestamp: "2026-02-13T14:05:00",
            },
            {
                id: 3,
                senderId: "customer",
                text: "Perfect! See you then",
                timestamp: "2026-02-13T14:10:00",
            },
            {
                id: 4,
                senderId: 2,
                text: "Thank you for the great review!",
                timestamp: "2026-02-13T17:30:00",
            },
        ],
    },
];

export const mockUser = {
    id: "customer-1",
    name: "Amit Kumar",
    email: "amit.kumar@example.com",
    phone: "+91 98765 43210",
    avatar: "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?w=200",
    role: "customer",
    verified: true,
    memberSince: "2025-08-15",
    totalBookings: 12,
    activeBookings: 2,
};

export const mockHelperProfile = {
    id: "helper-1",
    name: "Priya Sharma",
    email: "priya.sharma@example.com",
    phone: "+91 98765 12345",
    avatar: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?w=200",
    role: "helper",
    verified: true,
    memberSince: "2024-03-20",
    rating: 4.8,
    reviewCount: 127,
    completedJobs: 134,
    earnings: {
        total: 67000,
        thisMonth: 8500,
        pending: 1200,
    },
    availability: ["Monday", "Wednesday", "Friday", "Saturday"],
    hourlyRate: 250,
    categories: ["Event Support", "Elder Care", "Home Functions"],
    bio: "Experienced in elderly care and event management. Verified and trusted by 100+ families.",
};

export const mockStats = {
    totalHelpers: 1247,
    totalCustomers: 8932,
    completedBookings: 15678,
    activeBookings: 234,
    totalRevenue: 2847650,
    monthlyRevenue: 347890,
};
